### ISSUE TITLE
Fast A-Kaze occasionally segfaults on Linux

### ISSUE THREAD

**Issue by h2suzuki** [h2suzuki/fast_akaze#2]
Reported by Pablo, the original author of A-Kaze.

**Comment by h2suzuki** [comment]
The following commit fixes this issue
- 6616328  Fix the regression due to the overuse of std::ref()

**Comment by h2suzuki** [comment]
The fix has been verified by the reporter.  I'm closing the issue.

**Comment by h2suzuki** [comment]
The fix has been verified by the reporter. I'm closing the issue.

**Comment by dixitgoyal** [comment]
@h2suzuki  can you please help me in installing it with OpenfSM on ubuntu server?
